In [2]:
import torch
import math

In [3]:
# get int timesteps od shape (B, )
t = torch.arange(0, 10)
d_model = 384
half = d_model // 2

In [4]:
freqs = torch.exp(
    -math.log(10000) * torch.arange(half) / (half - 1)
)

In [5]:
freqs.shape

torch.Size([192])

In [6]:
t.shape

torch.Size([10])

In [15]:
t[:, None].shape

torch.Size([10, 1])

In [18]:
t[:, None].float()

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [23]:
freqs.shape

torch.Size([192])

In [24]:
freqs[None].shape

torch.Size([1, 192])

In [ ]:
args = t[:, None].float() * freqs[None]   # multiplying vectors of shape: t: (10,1) and freqs: (1, d_model // 2)  = (10, d_model // 2)

In [26]:
args.shape

torch.Size([10, 192])

In [8]:
torch.sin(args).shape

torch.Size([10, 192])

In [9]:
torch.cos(args).shape

torch.Size([10, 192])

### class embeddings

In [10]:
# get 32 random values in range [0, 10] 
y = torch.randint(0, 10, (32,))
y.shape

torch.Size([32])

In [ ]:
# The torch.rand function in PyTorch returns a tensor filled with random numbers drawn from a uniform distribution on the interval \([0, 1)\).
torch.rand(y.shape[0])

tensor([0.3660, 0.7573, 0.8963, 0.0290, 0.0914, 0.8673, 0.2617, 0.3350, 0.4618,
        0.9468, 0.1393, 0.1505, 0.0515, 0.5502, 0.9712, 0.8211, 0.6828, 0.2638,
        0.8274, 0.5725, 0.0108, 0.8081, 0.9583, 0.9494, 0.5078, 0.6644, 0.8026,
        0.6069, 0.7481, 0.4181, 0.5201, 0.8856])

In [12]:
torch.rand(y.shape[0]) < 0.1  #mask for all probs that are less than 0.1
# to mask out 10% of the labels from the batch

tensor([False, False, False,  True, False, False, False, False, False, False,
         True, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,  True,
        False, False])

In [ ]:
x = torch.ones(2, 3)
torch.full_like(x, 3.141592) # returns a tensor of the same shape as x, filled with the value 3.141592

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [14]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)

In [15]:
x

tensor([[-0.9347, -1.0177],
        [-1.1546,  0.7097],
        [-0.4419,  1.2843]])

In [16]:
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.where(x > 0, 1.0, 0.0) # returns a tensor of the same shape as x, where each element is 1.0 if the corresponding element in x is greater than 0, and 0.0 otherwise

tensor([[0., 0.],
        [0., 1.],
        [0., 1.]])

In [31]:
y = torch.randint(0, 10, (4,))

In [32]:
y.shape

torch.Size([4])

In [33]:
dropout_prob = 0.5
null_token = 10

In [34]:
drop_mask = torch.rand(y.shape[0], device=y.device) < dropout_prob

In [ ]:
drop_mask 

tensor([False,  True, False, False])

In [ ]:
y = torch.where(drop_mask, torch.full_like(y, null_token), y)  # overlay mask on y, put null on y indexes where mask is True

In [37]:
y

tensor([ 4, 10,  6,  2])